### ISSUE TITLE
Issue on Windows.

### ISSUE THREAD

**Issue by robin-173** [173TECH/sayn#35]
There is currently an issue on Windows which prevents SAYN to run. Please see attachments.

![image](https://user-images.githubusercontent.com/56123957/91964225-c8a40300-ed06-11ea-9c03-efaae1ffbc26.png)

[Windows Sayn Error Traceback.txt](https://github.com/173TECH/sayn/files/5161320/Windows.Sayn.Error.Traceback.txt)

**Comment by robin-173** [comment]
From Adrian: 
the issue is probably here:
https://github.com/173TECH/sayn/blob/9c4a0583c4467cb0ea5197858fb0ecda6ad33d8e/sayn/tasks/sql.py#L71

jinja seems to do something weird with file paths
removing the `str` might work

**Comment by iadrich** [comment]
The issue above is solved in 0.4, however Windows makes environment variables upper case, but SAYN expects the same case as the names internally. Example execution on Github Actions: https://github.com/173TECH/sayn/pull/71/checks?check_run_id=1308232133
