### ISSUE TITLE
Humanising Errors

### ISSUE THREAD

**Issue by robin-173** [173TECH/sayn#56]
We need to make the following error messages human friendly.

- [ ] Running SAYN outside of the project folder: `Result.Err (parsing::read_file_error): {'filename': PosixPath('project.yaml')}`
- [ ] An invalid task type (also breaks the spinner): `Result.Err (task_type::invalid_task_type_error): {'type': 'nodummy'}`
- [ ] Exceptions print the error twice: first line is the exception message, then comes the traceback and when the message is long it covers the whole screen. Particularly problematic with DBI exceptions

**Comment by TimofeySugaipov** [comment]
#77
